image:
  file: .gitpod.Dockerfile

tasks:
  - name: Redis
    command: |
      redis-server
  - name: Terminal
    command: |
      ls
ports:
  - port: 8080
    visibility: public
  - port: 4000
    visibility: public
  - port: 6379
    visibility: private
  - port: 3306
    visibility: private
  - port: 2379-36663
    onOpen: ignore